import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/Link';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Relief Pitcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a className={styles.linkColor} href="https://www.restaurantware.com/blog/post/what-are-the-different-types-of-beer/" target="_blank" rel="noreferrer">Relief Pitcher</a>
        </h1>

        <h3>
          Are you over 21?
        </h3>

        <div className={styles.grid}>
          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a> */}

          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a> */}

          <Link href='/deny'>
            <a className={styles.card}>
              <h2>No &#10060;</h2>
              <p>Honesty is the best policy&#46; Come back when you&#39;re 21</p>
            </a>
          </Link>

          <Link href='/search'>
            <a
              className={styles.card}
            >
              <h2>Yes &#9989;</h2>
              <p>
                You will be redirected to get your drink on!
              </p>
            </a>
          </Link>

        </div>
      </main>
    </div>
  )
}
